### ISSUE TITLE
Version 0.6.0 is not available on maven central

### ISSUE THREAD

**Issue by prathamesh13** [CadixDev/licenser#27]
The latest version of licenser i.e. 0.6.0 is not yet available at [https://mvnrepository.com/artifact/org.cadixdev.licenser/org.cadixdev.licenser.gradle.plugin](https://mvnrepository.com/artifact/org.cadixdev.licenser/org.cadixdev.licenser.gradle.plugin). 
Is this plugin still being published to maven central or has it been stopped?

**Comment by jamierocks** [comment]
No versions of licenser are published to Maven Central, just Gradle's repo.
