### ISSUE TITLE
License file incompatibilities with 0.6.0

### ISSUE THREAD

**Issue by NotMyFault** [CadixDev/licenser#29]
Hello,

I recently updated the licenser to 0.6.0 across my repositories but for some reason one did not work out as expected.
This is the license: https://github.com/IntellectualSites/PlotSquared/blob/v6/HEADER.txt
When trying to compile the project, I receive the following:

> Task :PlotSquared-Bukkit:checkLicenseMain FAILED
>Execution failed for task ':PlotSquared-Bukkit:checkLicenseMain'.
> Header does not contain any of the required keywords: map(extension 'license' property 'keywords')

The full exception can be found at https://gist.github.com/NotMyFault/f45a40a92e4d87d69742df1ef3591a0d

Am I missing something that requires some adjustments to the file itself? 

Thanks in advance.

**Comment by jamierocks** [comment]
Could you Gist your buildscript?

**Comment by NotMyFault** [comment]
I quickly pushed the licenser update to a separate branch https://github.com/IntellectualSites/PlotSquared/blob/feature/v6/update-licenser/build.gradle.kts

**Comment by NotMyFault** [comment]
Instead of using
```kt
configure<LicenseExtension> {
        header.set(resources.text.fromFile(file("HEADER.txt")))
        include("**/*.java")
        newLine.set(false)
}
```
Using 
```kt
configure<LicenseExtension> {
        header(rootProject.file("HEADER.txt"))
        include("**/*.java")
        newLine.set(false)
}
```
fixed it for me. Looks like I better call the file directly (on multi module projects).
